### ISSUE TITLE
Make RPTests create the RPTestApp in debug mode [2]

### ISSUE THREAD

**Issue by richardebeling** [HPI-SWA-Teaching/SWT15-Project-01#102]
### Subject
Currently, our RPTests creates a RPTestApp not in debug mode, thus the errors are often delayed and not as helpful as possible.

### Tasks / Acceptance Criteria
- [ ] Change `RPTests>> setUp` method to create the TestApp in debug mode.

### Efford estimation
2

**Comment by essal0815** [comment]
2

**Comment by schnaaabeltier** [comment]
3

**Comment by ninaihde** [comment]
2 (3)

**Comment by essal0815** [comment]
Chris Estimation: 2

**Comment by skydivin4ng3l** [comment]
setDebugMode is a methode in HttpService which can be used to fix this issue

**Comment by richardebeling** [comment]
I just did this temporarily with @jakobmache to debug failing tests. We have one test that tests that we get a 500 page when we raise an error in the handler. For this specific test, the debug mode has to be disabled. This should be done in the test itself.

**Comment by essal0815** [comment]
What do you mean with temporarily ?
If you fixed it, then just push it or ? If we want to be correct, open a pull request for the 5lines code ;) Or merge it directly.

**Comment by richardebeling** [comment]
Well, this exact issue kept him from debugging other errors, so I temporarily did the change on his PC. We fixed the wrong code, but then reverted the changes since they lead to test failures.

All I wanted to say is that the change will lead to a failing test, we will have to adapt the test. 

I can do this, I just thought it would be an easy thing for @skydivin4ng3l or @Nina510.

**Comment by essal0815** [comment]
We thought this is already done so we try to fix the both other issues.
Already assigned to them.

So my suggestion for this week:
* @jakobmache does the 2 Point Issue + merging his branch
* @Nina510, @skydivin4ng3l  and @essal0815 do the both other issues
* @He3lixxx do the review of our issues and thinks about refactoring the RPModel and RefClass relation (see RPModel class side #refClass)

At the moment we have a RPModel which has a RefClass which describes the structure of the objects handled by the model. (for example see RPTestModel and RPTestClass)
We have a lot of functions on the class side of RPModel because we don't have a generic RPModelClass / RPStructureGivingModelClass...
For example at the moment we are writing a method like: 
`updateCurrentObject: anObjectFromDatabase withNewJson: aJsonObject`
And we have to write this on ClassSide of RPModel, because we can't define on the instance side.

In general we 3 don't get the usage of  RPModel as a wrapper for data. From the database we get a RPModel object which contains the data object inside as instance variable. So we have to extract the data object which is an instance from the reference class ( `RPModel class refClass` ).
Why is this abstraction useful?

My suggestion would be, If its not useful, maybe we can put all data in The RPModel subclasses.
If the abstraction is useful, than please give us a short explanation. Then we ca think about a abstract RPModelClass (compare RPTestModel and RPTestClass).

**Comment by richardebeling** [comment]
Since this is something new, I put it into #106. @essal0815, please read through it and check if I understood correctly.

**Comment by richardebeling** [comment]
Closed in #107
