### ISSUE TITLE
Last Week: Tidy up github for the next group

### ISSUE THREAD

**Issue by essal0815** [HPI-SWA-Teaching/SWT15-Project-01#116]
- [x] Squeak Helper -> Dokus
- [x] ReadMe adjust
- [x] Example in Baseline
- [x] Issues tidy up, (make understandable)
- [x] contact @tom95 when session middleware completed

**Comment by richardebeling** [comment]
I looked through the issues and think we can leave them the way they are now.

**Comment by skydivin4ng3l** [comment]
Does anyone know how to operate the Squeak Helper, How to add stuff?

How should the ReadMe be adjusted? What is to do there?

Which examples should be added to the baseline how does this work?

**Comment by skydivin4ng3l** [comment]
Working on the Help in Squeak.

Setting up the basics contents have to be discussed further

A basic version is implemented contents copied from the Wiki is available as PR.

**Comment by richardebeling** [comment]
@essal0815 What do you mean with "Example in Baseline"? Do you mean adding the example app @jakobmache made to the baseline? Because I think we don't need to edit the baseline for that. The templates are not mentioned in the baseline either, so either it was already broken when we got it or it's fine without. What do you think?

Edit: Closing this. Repoen if you disagree.
